<?php
/**
 * @var \Magebit\Faq\Block\QuestionList $block
 */
?>
<?php $questions = $block->getQuestions(); ?>
<h1 class="faq-title">Frequently Asked Questions</h1>
<?php if ($questions->count()): ?>
    <div class="faq-questions">
        <ul class="faq-accordion" data-mage-init='{"accordion":{"active": false, "multipleCollapsible": true}}'>
            <?php foreach ($questions as $question): ?>
                <li class="faq-whole-question">
                    <div class="faq-question">
                    <div class="faq-question-text"><?= $escaper->escapeHtml($question->getQuestion()) ?></div>
                    </div>
                    <?php if ($question->getAnswer()): ?>
                        <div class="faq-answer" data-role="content">
                            <div class="faq-answer-text"><?= $escaper->escapeHtml($question->getAnswer()) ?></div>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php else: ?>
    <p>No questions to display.</p>
<?php endif; ?>
